export type PropType = 'text' | 'number' | 'boolean' | 'select' | 'color' | 'image' | 'list';

export interface PropSchemaItem {
  key: string;
  label: string;
  type: PropType;
  options?: { label: string; value: any }[]; // For 'select' type
}

export interface ComponentRegistryItem {
  category: 'Layout' | 'Content' | 'Interactive' | 'Sections' | 'E-commerce' | 'Basics';
  label: string;
  defaultProps: Record<string, any>;
  propSchema: PropSchemaItem[];
}

export const COMPONENT_REGISTRY: Record<string, ComponentRegistryItem> = {
  // Layout Group
  Section: {
    category: 'Layout',
    label: 'Section Wrapper',
    defaultProps: { backgroundColor: 'transparent', paddingTop: '4rem', paddingBottom: '4rem' },
    propSchema: [
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'paddingTop', label: 'Padding Top', type: 'text' },
      { key: 'paddingBottom', label: 'Padding Bottom', type: 'text' },
    ],
  },
  Container: {
    category: 'Layout',
    label: 'Max-Width Container',
    defaultProps: { maxWidth: '1200px', centered: true },
    propSchema: [
      { key: 'maxWidth', label: 'Max Width', type: 'text' },
      { key: 'centered', label: 'Center Container', type: 'boolean' },
    ],
  },
  Grid: {
    category: 'Layout',
    label: 'Responsive Grid',
    defaultProps: { columns: 3, gap: '1.5rem', responsive: true },
    propSchema: [
      { key: 'columns', label: 'Grid Columns', type: 'number' },
      { key: 'gap', label: 'Gap Spacing', type: 'text' },
      { key: 'responsive', label: 'Responsive Auto-fit', type: 'boolean' },
    ],
  },
  Column: {
    category: 'Layout',
    label: 'Grid Column',
    defaultProps: { span: 1, flex: '1' },
    propSchema: [
      { key: 'span', label: 'Column Span', type: 'number' },
      { key: 'flex', label: 'Flex Grow', type: 'text' },
    ],
  },
  Spacer: {
    category: 'Layout',
    label: 'Whitespace Spacer',
    defaultProps: { height: '2rem', width: '100%' },
    propSchema: [
      { key: 'height', label: 'Height', type: 'text' },
      { key: 'width', label: 'Width', type: 'text' },
    ],
  },

  // Content Group
  Heading: {
    category: 'Content',
    label: 'Typography: Heading',
    defaultProps: { text: 'Your Heading', level: 2, align: 'left', color: '#ffffff', marginBottom: '1rem' },
    propSchema: [
      { key: 'text', label: 'Text', type: 'text' },
      { key: 'level', label: 'Level (H1-H6)', type: 'number' },
      { key: 'align', label: 'Alignment', type: 'select', options: [
        { label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }
      ]},
      { key: 'color', label: 'Text Color', type: 'color' },
      { key: 'marginBottom', label: 'Margin Bottom', type: 'text' },
    ],
  },
  Paragraph: {
    category: 'Content',
    label: 'Typography: Paragraph',
    defaultProps: { text: 'Your paragraph text goes here.', align: 'left', color: '#a1a1aa', fontSize: '1.1rem' },
    propSchema: [
      { key: 'text', label: 'Content', type: 'text' },
      { key: 'align', label: 'Alignment', type: 'select', options: [
        { label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }
      ]},
      { key: 'color', label: 'Text Color', type: 'color' },
      { key: 'fontSize', label: 'Font Size', type: 'text' },
    ],
  },
  List: {
    category: 'Content',
    label: 'Typography: List',
    defaultProps: { items: ['Item 1', 'Item 2', 'Item 3'], type: 'bullet', color: '#a1a1aa' },
    propSchema: [
      { key: 'items', label: 'List Items', type: 'list' },
      { key: 'type', label: 'List Type', type: 'select', options: [
        { label: 'Bullet', value: 'bullet' }, { label: 'Ordered', value: 'ordered' }, { label: 'Checkmark', value: 'check' }
      ]},
      { key: 'color', label: 'Text Color', type: 'color' },
    ],
  },
  Image: {
    category: 'Content',
    label: 'Media: Image',
    defaultProps: { src: '', alt: 'Image', width: '100%', height: 'auto', borderRadius: '12px' },
    propSchema: [
      { key: 'src', label: 'Image URL', type: 'image' },
      { key: 'alt', label: 'Alt Text', type: 'text' },
      { key: 'width', label: 'Width', type: 'text' },
      { key: 'height', label: 'Height', type: 'text' },
      { key: 'borderRadius', label: 'Rounded Corners', type: 'text' },
    ],
  },
  Icon: {
    category: 'Content',
    label: 'Media: Icon',
    defaultProps: { iconName: 'Star', size: 24, color: '#6366f1' },
    propSchema: [
      { key: 'iconName', label: 'Lucide Icon Name', type: 'text' },
      { key: 'size', label: 'Icon Size (px)', type: 'number' },
      { key: 'color', label: 'Icon Color', type: 'color' },
    ],
  },

  // Interactive Group
  Tabs: {
    category: 'Interactive',
    label: 'Interactive: Tabs',
    defaultProps: { tabStyle: 'underline', activeColor: '#6366f1' },
    propSchema: [
      { key: 'items', label: 'Tabs (Label/Content)', type: 'list' },
      { key: 'tabStyle', label: 'Style', type: 'select', options: [{label: 'Underline', value: 'underline'}, {label: 'Pills', value: 'pills'}] },
      { key: 'activeColor', label: 'Active Color', type: 'color' },
    ],
  },
  Modal: {
    category: 'Interactive',
    label: 'Interactive: Modal',
    defaultProps: { triggerText: 'Open Modal', title: 'Modal Title', buttonVariant: 'primary' },
    propSchema: [
      { key: 'triggerText', label: 'Trigger Button Text', type: 'text' },
      { key: 'title', label: 'Modal Title', type: 'text' },
      { key: 'content', label: 'Modal Content', type: 'text' },
      { key: 'buttonVariant', label: 'Button Style', type: 'select', options: [{label: 'Primary', value: 'primary'}, {label: 'Secondary', value: 'secondary'}, {label: 'Outline', value: 'outline'}] },
    ],
  },
  Form: {
    category: 'Interactive',
    label: 'Interactive: Full Form',
    defaultProps: { title: 'Contact Us', description: 'Enter details below', buttonLabel: 'Send' },
    propSchema: [
      { key: 'title', label: 'Form Title', type: 'text' },
      { key: 'description', label: 'Form Description', type: 'text' },
      { key: 'buttonLabel', label: 'Submit Button Label', type: 'text' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
    ],
  },

  // Forms Category (Individual Elements)
  Input: {
    category: 'Basics', // Using Basics for form elements
    label: 'Form: Input',
    defaultProps: { label: 'Label', placeholder: 'Enter text...', type: 'text' },
    propSchema: [
      { key: 'label', label: 'Label', type: 'text' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'type', label: 'HTML Type', type: 'select', options: [{label: 'Text', value: 'text'}, {label: 'Email', value: 'email'}, {label: 'Number', value: 'number'}] },
    ],
  },
  Checkbox: {
    category: 'Basics',
    label: 'Form: Checkbox',
    defaultProps: { label: 'Check this box' },
    propSchema: [{ key: 'label', label: 'Label', type: 'text' }],
  },
  Submit: {
    category: 'Basics',
    label: 'Form: Submit Button',
    defaultProps: { label: 'Submit', width: 'w-full' },
    propSchema: [
      { key: 'label', label: 'Label', type: 'text' },
      { key: 'width', label: 'Width (Tailwind)', type: 'text' },
    ],
  },

  // Advanced Group
  Card: {
    category: 'Basics',
    label: 'Layout: Card',
    defaultProps: { padding: '1.5rem', backgroundColor: '#18181b', borderRadius: '16px', hoverEffect: true },
    propSchema: [
      { key: 'padding', label: 'Padding', type: 'text' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'borderRadius', label: 'Border Radius', type: 'text' },
      { key: 'hoverEffect', label: 'Enable Hover Effect', type: 'boolean' },
    ],
  },
  PricingCard: {
    category: 'Sections',
    label: 'Advanced: Pricing Card',
    defaultProps: { plan: 'Pro', price: '$49', isPopular: true, features: ['Unlimited Sites', '24/7 Support', 'Custom Domain'] },
    propSchema: [
      { key: 'plan', label: 'Plan Name', type: 'text' },
      { key: 'price', label: 'Price', type: 'text' },
      { key: 'features', label: 'Features', type: 'list' },
      { key: 'isPopular', label: 'Popular Badge', type: 'boolean' },
      { key: 'accentColor', label: 'Accent Color', type: 'color' },
    ],
  },
  BlogCard: {
    category: 'Sections',
    label: 'Modern Blog Card',
    defaultProps: {
      title: 'Modern Web Design',
      author: 'Admin',
      category: 'Design',
      excerpt: 'Discover the latest trends in modern web design...',
      date: 'Dec 15, 2026',
      readTime: '5 min read',
      cardBackground: '#18181b',
      cardBorderColor: '#27272a',
      accentColor: '#6366f1',
      titleColor: '#ffffff',
      textColor: '#ffffff',
      subtextColor: '#a1a1aa',
      categoryBackground: '#6366f1',
      categoryColor: '#ffffff',
    },
    propSchema: [
      { key: 'title', label: 'Headline', type: 'text' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'excerpt', label: 'Excerpt', type: 'text' },
      { key: 'author', label: 'Author Name', type: 'text' },
      { key: 'date', label: 'Published Date', type: 'text' },
      { key: 'image', label: 'Thumbnail Image', type: 'image' },
      { key: 'cardBackground', label: 'Card Background', type: 'color' },
      { key: 'cardBorderColor', label: 'Card Border Color', type: 'color' },
      { key: 'accentColor', label: 'Accent / Glow Color', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'textColor', label: 'Body Text Color', type: 'color' },
      { key: 'subtextColor', label: 'Meta Text Color', type: 'color' },
      { key: 'categoryBackground', label: 'Category Badge Color', type: 'color' },
    ],
  },
  Testimonial: {
    category: 'Sections',
    label: 'Advanced: Testimonial',
    defaultProps: { author: 'Jane Cooper', role: 'Designer', quote: 'This builder is amazing!' },
    propSchema: [
      { key: 'author', label: 'Author Name', type: 'text' },
      { key: 'role', label: 'Role/Company', type: 'text' },
      { key: 'quote', label: 'Testimonial Text', type: 'text' },
      { key: 'avatar', label: 'Avatar URL', type: 'image' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
    ],
  },

  HeroTemplate: {
    category: 'Sections',
    label: 'Advanced: Hero Layout',
    defaultProps: { title: 'Hero Headline', alignment: 'left', ctaText: 'Get Started', ctaLink: '#' },
    propSchema: [
      { key: 'title', label: 'Headline', type: 'text' },
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'ctaText', label: 'Button Text', type: 'text' },
      { key: 'ctaLink', label: 'Button Link / Page', type: 'text' },
      { key: 'image', label: 'Hero Image', type: 'image' },
      { key: 'alignment', label: 'Alignment', type: 'select', options: [{label: 'Left', value: 'left'}, {label: 'Center', value: 'center'}] },
    ],
  },

  // Global / Layout
  Navbar: {
    category: 'Sections',
    label: 'Navigation: Standard',
    defaultProps: {
      logoText: 'PraiSol',
      logoImage: '',
      links: [
        { label: 'Home', href: '/' },
        { label: 'About', href: '/about' },
        { label: 'Contact', href: '/contact' },
      ],
      showCTA: true,
      ctaLabel: 'Get Started',
      ctaLink: '/contact',
      backgroundColor: '#09090b',
      sticky: true,
    },
    propSchema: [
      { key: 'logoImage', label: 'Logo Image', type: 'image' },
      { key: 'logoText', label: 'Brand Name', type: 'text' },
      { key: 'logoHeight', label: 'Logo Height (px)', type: 'number' },
      { key: 'links', label: 'Navigation Links', type: 'list' },
      { key: 'linkWeight', label: 'Font Weight', type: 'select', options: [{label: 'Normal', value: 'normal'}, {label: 'Medium', value: 'medium'}, {label: 'Semibold', value: 'semibold'}, {label: 'Bold', value: 'bold'}] },
      { key: 'activeColor', label: 'Active Link Color', type: 'color' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'sticky', label: 'Sticky Header', type: 'boolean' },
      { key: 'showCTA', label: 'Show CTA Button', type: 'boolean' },
      { key: 'ctaLabel', label: 'CTA Label', type: 'text' },
      { key: 'ctaLink', label: 'CTA Link', type: 'text' },
    ],
  },

  NavbarCentered: {
    category: 'Sections',
    label: 'Navigation: Centered Logo',
    defaultProps: {
      logoText: 'PraiSol',
      links: [
        { label: 'Home', href: '/' },
        { label: 'Services', href: '/services' },
        { label: 'About', href: '/about' },
        { label: 'Contact', href: '/contact' },
      ],
      showCTA: true,
      ctaLabel: 'Get Started',
      ctaLink: '/contact',
      backgroundColor: '#09090b',
      sticky: true,
    },
    propSchema: [
      { key: 'logoImage', label: 'Logo Image', type: 'image' },
      { key: 'logoText', label: 'Brand Name', type: 'text' },
      { key: 'logoHeight', label: 'Logo Height (px)', type: 'number' },
      { key: 'links', label: 'Navigation Links', type: 'list' },
      { key: 'linkWeight', label: 'Font Weight', type: 'select', options: [{label: 'Normal', value: 'normal'}, {label: 'Medium', value: 'medium'}, {label: 'Semibold', value: 'semibold'}, {label: 'Bold', value: 'bold'}] },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'sticky', label: 'Sticky Header', type: 'boolean' },
      { key: 'showCTA', label: 'Show CTA Button', type: 'boolean' },
      { key: 'ctaLabel', label: 'CTA Label', type: 'text' },
      { key: 'ctaLink', label: 'CTA Link', type: 'text' },
    ],
  },

  NavbarGlass: {
    category: 'Sections',
    label: 'Navigation: Modern Glass',
    defaultProps: {
      logoText: 'PraiSol',
      links: [
        { label: 'Home', href: '/' },
        { label: 'Features', href: '/features' },
        { label: 'Pricing', href: '/pricing' },
        { label: 'About', href: '/about' },
      ],
      showCTA: true,
      ctaLabel: 'Sign Up',
      ctaLink: '/signup',
      backgroundColor: '#000000',
      sticky: true,
    },
    propSchema: [
      { key: 'logoText', label: 'Brand Name', type: 'text' },
      { key: 'links', label: 'Navigation Links', type: 'list' },
      { key: 'showCTA', label: 'Show CTA Button', type: 'boolean' },
      { key: 'ctaLabel', label: 'CTA Label', type: 'text' },
      { key: 'ctaLink', label: 'CTA Link', type: 'text' },
      { key: 'backgroundColor', label: 'Main Theme Color', type: 'color' },
    ],
  },

  Button: {
    category: 'Basics',
    label: 'Call to Action Button',
    defaultProps: {
      label: 'Click Me',
      link: '#',
      variant: 'primary',
      size: 'md',
    },
    propSchema: [
      { key: 'label', label: 'Button Label', type: 'text' },
      { key: 'link', label: 'Link URL / Page', type: 'text' },
      { key: 'variant', label: 'Style Variant', type: 'select', options: [
        { label: 'Primary', value: 'primary' },
        { label: 'Secondary', value: 'secondary' },
        { label: 'Outline', value: 'outline' },
        { label: 'Ghost', value: 'ghost' },
      ]},
      { key: 'size', label: 'Button Size', type: 'select', options: [
        { label: 'Small', value: 'sm' },
        { label: 'Medium', value: 'md' },
        { label: 'Large', value: 'lg' },
      ]},
    ]
  },

  // School / College Sections
  Hero: {
    category: 'Sections',
    label: 'Hero Section',
    defaultProps: {
      title: 'Welcome to Our Institution',
      subtitle: 'Shaping the future of education with excellence and innovation.',
      backgroundImage: '',
      backgroundColor: '#09090b',
      overlayOpacity: 30,
      textAlign: 'center',
      titleColor: '#ffffff',
      subtitleColor: '#a1a1aa',
      ctaText: 'Apply Now',
      ctaLink: '/admissions',
      ctaVariant: 'primary',
      showSecondaryBtn: true,
      secondaryCtaText: 'Learn More',
      secondaryCtaLink: '#',
      paddingTop: '5rem',
      paddingBottom: '5rem',
      minHeight: '500px',
      showBadge: false,
      badgeText: '🎉 Admissions Open 2026',
    },
    propSchema: [
      { key: 'title', label: 'Headline', type: 'text' },
      { key: 'subtitle', label: 'Sub-headline', type: 'text' },
      { key: 'backgroundImage', label: 'Background Image', type: 'image' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'overlayOpacity', label: 'Image Overlay Opacity (0-100)', type: 'number' },
      { key: 'textAlign', label: 'Text Alignment', type: 'select', options: [{label: 'Left', value: 'left'}, {label: 'Center', value: 'center'}, {label: 'Right', value: 'right'}] },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'subtitleColor', label: 'Subtitle Color', type: 'color' },
      { key: 'showBadge', label: 'Show Badge', type: 'boolean' },
      { key: 'badgeText', label: 'Badge Text', type: 'text' },
      { key: 'ctaText', label: 'Primary Button Text', type: 'text' },
      { key: 'ctaLink', label: 'Primary Button Link', type: 'text' },
      { key: 'ctaVariant', label: 'Primary Button Style', type: 'select', options: [{label: 'Primary', value: 'primary'}, {label: 'Secondary', value: 'secondary'}, {label: 'Outline', value: 'outline'}, {label: 'Ghost', value: 'ghost'}] },
      { key: 'showSecondaryBtn', label: 'Show Secondary Button', type: 'boolean' },
      { key: 'secondaryCtaText', label: 'Secondary Button Text', type: 'text' },
      { key: 'secondaryCtaLink', label: 'Secondary Button Link', type: 'text' },
      { key: 'paddingTop', label: 'Padding Top', type: 'text' },
      { key: 'paddingBottom', label: 'Padding Bottom', type: 'text' },
      { key: 'minHeight', label: 'Min Height', type: 'text' },
    ],
  },

  NewsFeed: {
    category: 'Content',
    label: 'News & Announcements',
    defaultProps: {
      title: 'Latest News & Updates',
      news: [
        { id: 1, title: 'Annual Sports Day 2026 Announced', date: 'Oct 20, 2025', summary: 'The much awaited annual sports day...' },
      ],
      backgroundColor: '#18181b',
      cardBackground: '#09090b',
      cardBorderColor: '#27272a',
      accentColor: '#6366f1',
      titleColor: '#ffffff',
      textColor: '#ffffff',
      subtextColor: '#a1a1aa',
      padding: '2rem',
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'news', label: 'News Items list', type: 'list' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'cardBackground', label: 'Item Background', type: 'color' },
      { key: 'cardBorderColor', label: 'Border Color', type: 'color' },
      { key: 'accentColor', label: 'Accent / Icon Color', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'textColor', label: 'Headline Color', type: 'color' },
      { key: 'subtextColor', label: 'Body Text Color', type: 'color' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  // Business / E-commerce
  ProductGrid: {
    category: 'E-commerce',
    label: 'Product Showcase',
    defaultProps: {
      title: 'Our Products',
      products: [
        { id: 1, name: 'Sample Product', price: '₹1,000', image: '' },
      ],
      showPrice: true,
      showCartButton: true,
      columns: 3,
      backgroundColor: '#09090b',
      titleColor: '#ffffff',
      cardBackground: '#18181b',
      cardBorderColor: '#27272a',
      accentColor: '#6366f1',
      priceColor: '#ffffff',
      textColor: '#ffffff',
      padding: '5rem 2rem',
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'products', label: 'Products list', type: 'list' },
      { key: 'showPrice', label: 'Show Prices', type: 'boolean' },
      { key: 'showCartButton', label: 'Show Add to Cart', type: 'boolean' },
      { key: 'columns', label: 'Grid Columns', type: 'number' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'cardBackground', label: 'Card Background', type: 'color' },
      { key: 'cardBorderColor', label: 'Card Border Color', type: 'color' },
      { key: 'accentColor', label: 'Accent / Button Color', type: 'color' },
      { key: 'priceColor', label: 'Price Text Color', type: 'color' },
      { key: 'textColor', label: 'Product Name Color', type: 'color' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },
  
  // School / College Sections
  StatsBar: {
    category: 'Sections',
    label: 'Statistics Bar',
    defaultProps: {
      stats: [
        { label: 'Students', value: '1000+' },
        { label: 'Teachers', value: '50+' },
        { label: 'Years', value: '25' },
      ],
      backgroundColor: '#111827',
      textColor: '#ffffff',
    },
    propSchema: [
      { key: 'stats', label: 'Statistics List', type: 'list' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'textColor', label: 'Text Color', type: 'color' },
    ],
  },

  GalleryGrid: {
    category: 'Content',
    label: 'Image Gallery',
    defaultProps: {
      title: 'Our Gallery',
      subtitle: 'Explore our moments and memories',
      showSubtitle: true,
      images: [
        { url: '', caption: 'Event 1' },
        { url: '', caption: 'Event 2' },
        { url: '', caption: 'Event 3' },
      ],
      columns: 3,
      backgroundColor: '#09090b',
      titleColor: '#ffffff',
      subtitleColor: '#a1a1aa',
      borderRadius: '12px',
      aspectRatio: '4/3',
      gap: '1rem',
      padding: '5rem 2rem',
      showCaptions: true,
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'subtitle', label: 'Subtitle', type: 'text' },
      { key: 'showSubtitle', label: 'Show Subtitle', type: 'boolean' },
      { key: 'images', label: 'Gallery Images list', type: 'list' },
      { key: 'columns', label: 'Max Columns', type: 'number' },
      { key: 'showCaptions', label: 'Show Image Captions', type: 'boolean' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'subtitleColor', label: 'Subtitle Color', type: 'color' },
      { key: 'borderRadius', label: 'Border Radius', type: 'text' },
      { key: 'aspectRatio', label: 'Aspect Ratio (e.g. 4/3, 1/1)', type: 'text' },
      { key: 'gap', label: 'Grid Gap', type: 'text' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  // Business / E-commerce
  PricingSection: {
    category: 'Sections',
    label: 'Pricing Tables',
    defaultProps: {
      title: 'Our Plans',
      subtitle: 'Choose the plan that fits your needs',
      plans: [
        { name: 'Starter', price: '$0', features: ['Basic features', 'Community support'], ctaText: 'Get Started' },
        { name: 'Professional', price: '$29', features: ['Advanced features', 'Priority support', 'Custom domain'], highlight: true, ctaText: 'Go Pro' },
        { name: 'Enterprise', price: 'Custom', features: ['Full features', 'dedicated account manager'], ctaText: 'Contact Us' },
      ],
      backgroundColor: '#09090b',
      cardBackground: '#18181b',
      cardBorderColor: '#27272a',
      accentColor: '#6366f1',
      highlightColor: 'rgba(99,102,241,0.06)',
      titleColor: '#ffffff',
      subtitleColor: '#a1a1aa',
      padding: '5rem 2rem',
      showBadge: true,
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'subtitle', label: 'Subtitle', type: 'text' },
      { key: 'plans', label: 'Pricing Plans list', type: 'list' },
      { key: 'showBadge', label: 'Show "Popular" Badge', type: 'boolean' },
      { key: 'accentColor', label: 'Accent / Brand Color', type: 'color' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'cardBackground', label: 'Card Background', type: 'color' },
      { key: 'cardBorderColor', label: 'Card Border Color', type: 'color' },
      { key: 'highlightColor', label: 'Highlighted Card BG', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'subtitleColor', label: 'Text Color', type: 'color' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  ContactSection: {
    category: 'Sections',
    label: 'Contact Info & Form',
    defaultProps: {
      title: 'Get in Touch',
      subtitle: 'We would love to hear from you. Reach out to us via any of the following channels.',
      email: 'contact@example.online',
      phone: '+91 8374950475',
      address: 'Anantapur, Andhra Pradesh, India',
      showForm: true,
      backgroundColor: '#09090b',
      cardBackground: '#18181b',
      cardBorderColor: '#27272a',
      accentColor: '#6366f1',
      titleColor: '#ffffff',
      textColor: '#ffffff',
      subtextColor: '#a1a1aa',
      padding: '5rem 2rem',
      formTitle: 'Send us a Message',
      buttonText: 'Send Message',
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'subtitle', label: 'Subtitle', type: 'text' },
      { key: 'email', label: 'Email Address', type: 'text' },
      { key: 'phone', label: 'Phone Number', type: 'text' },
      { key: 'address', label: 'Physical Address', type: 'text' },
      { key: 'showForm', label: 'Show Contact Form', type: 'boolean' },
      { key: 'formTitle', label: 'Form Title', type: 'text' },
      { key: 'buttonText', label: 'Button Text', type: 'text' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'cardBackground', label: 'Card Background', type: 'color' },
      { key: 'cardBorderColor', label: 'Card Border Color', type: 'color' },
      { key: 'accentColor', label: 'Accent / Button Color', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'textColor', label: 'Info Text Color', type: 'color' },
      { key: 'subtextColor', label: 'Label Text Color', type: 'color' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  // Personal Portfolio Sections
  ProjectGrid: {
    category: 'Sections',
    label: 'Portfolio Projects',
    defaultProps: {
      title: 'Featured Projects',
      projects: [
        { title: 'Project One', desc: 'A revolutionary app.', tags: ['React', 'Next.js'], link: '#', github: '#' },
        { title: 'Project Two', desc: 'Built for scale.', tags: ['Node.js', 'PostgreSQL'], link: '#', github: '#' },
      ],
      backgroundColor: '#09090b',
      titleColor: '#ffffff',
      cardBackground: '#18181b',
      cardBorderColor: '#27272a',
      accentColor: '#6366f1',
      tagColor: '#818cf8',
      tagBackground: 'rgba(99,102,241,0.1)',
      padding: '5rem 2rem',
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'projects', label: 'Projects list', type: 'list' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'cardBackground', label: 'Card Background', type: 'color' },
      { key: 'cardBorderColor', label: 'Card Border Color', type: 'color' },
      { key: 'accentColor', label: 'Accent Color', type: 'color' },
      { key: 'tagColor', label: 'Tag Text Color', type: 'color' },
      { key: 'tagBackground', label: 'Tag Background', type: 'color' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  ExperienceTimeline: {
    category: 'Sections',
    label: 'Work Experience',
    defaultProps: {
      title: 'Professional Journey',
      items: [
        { role: 'Senior Developer', company: 'Tech Corp', duration: '2021 - Present', current: true },
        { role: 'Junior Developer', company: 'StartUp Inc', duration: '2019 - 2021', current: false },
      ],
      backgroundColor: '#09090b',
      titleColor: '#ffffff',
      cardBackground: '#18181b',
      cardBorderColor: '#27272a',
      accentColor: '#6366f1',
      nodeColor: '#18181b',
      lineColor: '#27272a',
      padding: '5rem 2rem',
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'items', label: 'Experience items', type: 'list' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'cardBackground', label: 'Card Background', type: 'color' },
      { key: 'cardBorderColor', label: 'Card Border Color', type: 'color' },
      { key: 'accentColor', label: 'Accent Color', type: 'color' },
      { key: 'nodeColor', label: 'Timeline Node Color', type: 'color' },
      { key: 'lineColor', label: 'Timeline Line Color', type: 'color' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  SkillMatrix: {
    category: 'Sections',
    label: 'Skill Matrix',
    defaultProps: {
      title: 'Technical Arsenal',
      skills: [
        { name: 'JavaScript', proficiency: 95 },
        { name: 'React', proficiency: 90 },
        { name: 'TypeScript', proficiency: 85 },
        { name: 'Database', proficiency: 80 },
      ],
      backgroundColor: '#09090b',
      titleColor: '#ffffff',
      subtitleColor: '#a1a1aa',
      accentColor: '#6366f1',
      trackColor: '#18181b',
      barColor: 'linear-gradient(90deg, #6366f1, #a855f7)',
      padding: '5rem 2rem',
      columns: 2,
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'skills', label: 'Skills List', type: 'list' },
      { key: 'columns', label: 'Columns (1 or 2)', type: 'number' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'subtitleColor', label: 'Subtitle Color', type: 'color' },
      { key: 'accentColor', label: 'Accent Color', type: 'color' },
      { key: 'barColor', label: 'Progress Bar Color', type: 'text' },
      { key: 'trackColor', label: 'Track Color', type: 'color' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },
  
  // Basics / Atomic wrappers for the builder
  AccordionSection: {
    category: 'Sections',
    label: 'Accordion / FAQ List',
    defaultProps: {
      title: 'Frequently Asked Questions',
      items: [
        { title: 'Question 1', content: 'Answer 1' },
        { title: 'Question 2', content: 'Answer 2' },
      ],
      backgroundColor: '#09090b',
      titleColor: '#ffffff',
      itemTitleColor: '#ffffff',
      itemContentColor: '#a1a1aa',
      accentColor: '#6366f1',
      padding: '5rem 1.5rem',
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'items', label: 'Items List', type: 'list' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'titleColor', label: 'Section Title Color', type: 'color' },
      { key: 'itemTitleColor', label: 'Item Title Color', type: 'color' },
      { key: 'itemContentColor', label: 'Item Text Color', type: 'color' },
      { key: 'accentColor', label: 'Accent Color', type: 'color' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  FAQ: {
    category: 'Sections',
    label: 'Modern FAQ (Cards)',
    defaultProps: {
      items: [
        { question: 'What is PraiSol?', answer: 'PraiSol is an advanced website builder...' },
      ],
      backgroundColor: 'transparent',
      accentColor: '#6366f1',
      questionColor: '#ffffff',
      answerColor: '#a1a1aa',
      borderColor: '#27272a',
      borderRadius: '12px',
      padding: '4rem 2rem',
    },
    propSchema: [
      { key: 'items', label: 'FAQ Items list', type: 'list' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'accentColor', label: 'Accent Color', type: 'color' },
      { key: 'questionColor', label: 'Question Color', type: 'color' },
      { key: 'answerColor', label: 'Answer Color', type: 'color' },
      { key: 'borderColor', label: 'Border Color', type: 'color' },
      { key: 'borderRadius', label: 'Border Radius', type: 'text' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },
  
  FixedText: {
    category: 'Content',
    label: 'Fixed/Floating Text',
    defaultProps: {
      text: 'Floating Text',
      fontSize: '1rem',
      fontWeight: 'normal',
      color: '#ffffff',
      align: 'left',
      top: '',
      bottom: '20px',
      left: '',
      right: '20px',
      zIndex: 10,
      backgroundColor: 'transparent',
      padding: '10px',
      borderRadius: '8px',
    },
    propSchema: [
      { key: 'text', label: 'Text Content', type: 'text' },
      { key: 'fontSize', label: 'Font Size', type: 'text' },
      { key: 'fontWeight', label: 'Font Weight', type: 'select', options: [{ label: 'Normal', value: 'normal'}, { label: 'Medium', value: 'medium'}, { label: 'Semibold', value: 'semibold'}, { label: 'Bold', value: 'bold'}] },
      { key: 'color', label: 'Text Color', type: 'color' },
      { key: 'align', label: 'Text Alignment', type: 'select', options: [{ label: 'Left', value: 'left'}, { label: 'Center', value: 'center'}, { label: 'Right', value: 'right'}] },
      { key: 'top', label: 'Top Position', type: 'text' },
      { key: 'bottom', label: 'Bottom Position', type: 'text' },
      { key: 'left', label: 'Left Position', type: 'text' },
      { key: 'right', label: 'Right Position', type: 'text' },
      { key: 'zIndex', label: 'Z-Index (Layer)', type: 'number' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'text' },
      { key: 'borderRadius', label: 'Border Radius', type: 'text' },
    ],
  },

  // --- NEW COMPONENTS ---
  TeamGrid: {
    category: 'Sections',
    label: 'Team Members Grid',
    defaultProps: {
      title: 'Meet Our Team',
      subtitle: 'The talented people behind the scenes.',
      showSubtitle: true,
      members: [
        { name: 'Aarav Sharma', role: 'Founder & CEO', bio: 'Visionary leader.' },
        { name: 'Priya Mehta', role: 'CTO', bio: 'Platform architect.' },
        { name: 'Rohan Singh', role: 'Designer', bio: 'UX craftsman.' },
      ],
      columns: 3,
      accentColor: '#6366f1',
      backgroundColor: 'transparent',
      cardBackground: 'rgba(255,255,255,0.04)',
      borderColor: 'rgba(255,255,255,0.07)',
      titleColor: '#ffffff',
      subtitleColor: '#a1a1aa',
      showBio: true,
      avatarSize: 80,
      cardBorderRadius: '20px',
      padding: '4rem 2rem',
      layout: 'card',
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'subtitle', label: 'Subtitle', type: 'text' },
      { key: 'showSubtitle', label: 'Show Subtitle', type: 'boolean' },
      { key: 'members', label: 'Team Members list', type: 'list' },
      { key: 'columns', label: 'Columns', type: 'number' },
      { key: 'layout', label: 'Card Style', type: 'select', options: [{label: 'Card', value: 'card'}, {label: 'Minimal', value: 'minimal'}] },
      { key: 'showBio', label: 'Show Bio Text', type: 'boolean' },
      { key: 'avatarSize', label: 'Avatar Size (px)', type: 'number' },
      { key: 'accentColor', label: 'Accent Color', type: 'color' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'cardBackground', label: 'Card Background', type: 'color' },
      { key: 'borderColor', label: 'Card Border Color', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'subtitleColor', label: 'Subtitle Color', type: 'color' },
      { key: 'cardBorderRadius', label: 'Card Border Radius', type: 'text' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  VideoEmbed: {
    category: 'Content',
    label: 'Video Embed (YouTube/Vimeo)',
    defaultProps: {
      title: 'Watch Our Story',
      videoUrl: '',
      aspectRatio: '16/9',
      showCaption: true,
      caption: 'See how we are changing education.',
      accentColor: '#6366f1',
      backgroundColor: '#09090b',
      padding: '4rem 2rem',
      borderRadius: '20px',
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'videoUrl', label: 'Video URL (YouTube / Vimeo)', type: 'text' },
      { key: 'aspectRatio', label: 'Aspect Ratio (e.g. 16/9, 4/3)', type: 'text' },
      { key: 'showCaption', label: 'Show Caption', type: 'boolean' },
      { key: 'caption', label: 'Caption Text', type: 'text' },
      { key: 'accentColor', label: 'Border Glow Color', type: 'color' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'borderRadius', label: 'Border Radius', type: 'text' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  StatsCounter: {
    category: 'Sections',
    label: 'Stats / Counters',
    defaultProps: {
      title: 'By the Numbers',
      subtitle: 'Our impact in numbers',
      showTitle: true,
      stats: [
        { label: 'Students', value: '5,000+', icon: '🎓' },
        { label: 'Teachers', value: '150+', icon: '👩‍🏫' },
        { label: 'Years', value: '25', icon: '🏆' },
        { label: 'Alumni', value: '20,000+', icon: '🌐' },
      ],
      layout: 'row',
      accentColor: '#6366f1',
      backgroundColor: 'transparent',
      cardBackground: 'rgba(255,255,255,0.04)',
      borderColor: 'rgba(255,255,255,0.07)',
      titleColor: '#ffffff',
      subtitleColor: '#a1a1aa',
      showIcons: true,
      cardBorderRadius: '18px',
      padding: '4rem 2rem',
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'subtitle', label: 'Subtitle', type: 'text' },
      { key: 'showTitle', label: 'Show Title', type: 'boolean' },
      { key: 'stats', label: 'Stats List', type: 'list' },
      { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'Row (side-by-side)', value: 'row' }, { label: 'Grid (2-col)', value: 'grid' }] },
      { key: 'showIcons', label: 'Show Icons/Emoji', type: 'boolean' },
      { key: 'accentColor', label: 'Value Color (Accent)', type: 'color' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color' },
      { key: 'cardBackground', label: 'Card Background', type: 'color' },
      { key: 'borderColor', label: 'Card Border Color', type: 'color' },
      { key: 'titleColor', label: 'Title Color', type: 'color' },
      { key: 'subtitleColor', label: 'Subtitle Color', type: 'color' },
      { key: 'cardBorderRadius', label: 'Card Border Radius', type: 'text' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
    ],
  },

  Banner: {
    category: 'Sections',
    label: 'Announcement Banner',
    defaultProps: {
      text: '🚀 New session starting January 2026 — Limited seats!',
      subtext: '',
      ctaLabel: 'Apply Now',
      ctaLink: '#',
      showCta: true,
      backgroundColor: '#4f46e5',
      textColor: '#ffffff',
      accentColor: '#ffffff',
      fontSize: '0.95rem',
      padding: '0.85rem 2rem',
      borderRadius: '0px',
    },
    propSchema: [
      { key: 'text', label: 'Banner Message', type: 'text' },
      { key: 'subtext', label: 'Sub-text', type: 'text' },
      { key: 'showCta', label: 'Show CTA Button', type: 'boolean' },
      { key: 'ctaLabel', label: 'CTA Button Label', type: 'text' },
      { key: 'ctaLink', label: 'CTA Link', type: 'text' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'textColor', label: 'Text Color', type: 'color' },
      { key: 'accentColor', label: 'Button Color', type: 'color' },
      { key: 'fontSize', label: 'Font Size (e.g. 0.95rem)', type: 'text' },
      { key: 'padding', label: 'Padding (e.g. 0.85rem 2rem)', type: 'text' },
      { key: 'borderRadius', label: 'Border Radius', type: 'text' },
    ],
  },

  LogoCarousel: {
    category: 'Sections',
    label: 'Logo Carousel / Trusted By',
    defaultProps: {
      title: 'Trusted By',
      logos: [
        { name: 'Partner One' },
        { name: 'Partner Two' },
        { name: 'Partner Three' },
        { name: 'Partner Four' },
      ],
      backgroundColor: 'transparent',
      titleColor: '#71717a',
      logoOpacity: 0.6,
      logoHeight: 40,
      padding: '3rem 2rem',
      speed: 15,
    },
    propSchema: [
      { key: 'title', label: 'Section Label', type: 'text' },
      { key: 'logos', label: 'Partner Logos list', type: 'list' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'titleColor', label: 'Label Text Color', type: 'color' },
      { key: 'logoOpacity', label: 'Logo Opacity (0-1)', type: 'number' },
      { key: 'logoHeight', label: 'Logo Height (px)', type: 'number' },
      { key: 'padding', label: 'Section Padding', type: 'text' },
      { key: 'speed', label: 'Animation Speed (s)', type: 'number' },
    ],
  },

  Footer: {
    category: 'Sections',
    label: 'Site Footer',
    defaultProps: {
      brandName: 'PraiSol',
      tagline: 'Building the future, one site at a time.',
      showColumns: true,
      copyrightText: `© ${new Date().getFullYear()} PraiSol. All rights reserved.`,
      backgroundColor: '#09090b',
      accentColor: '#6366f1',
      textColor: '#71717a',
      borderColor: 'rgba(255,255,255,0.07)',
      showSocials: false,
      facebookUrl: '',
      twitterUrl: '',
      instagramUrl: '',
      linkedinUrl: '',
      youtubeUrl: '',
      padding: '4rem 2rem 2rem',
    },
    propSchema: [
      { key: 'brandName', label: 'Brand Name', type: 'text' },
      { key: 'tagline', label: 'Tagline', type: 'text' },
      { key: 'copyrightText', label: 'Copyright Text', type: 'text' },
      { key: 'showColumns', label: 'Show Link Columns', type: 'boolean' },
      { key: 'showSocials', label: 'Show Social Icons', type: 'boolean' },
      { key: 'facebookUrl', label: 'Facebook URL', type: 'text' },
      { key: 'twitterUrl', label: 'Twitter / X URL', type: 'text' },
      { key: 'instagramUrl', label: 'Instagram URL', type: 'text' },
      { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'text' },
      { key: 'youtubeUrl', label: 'YouTube URL', type: 'text' },
      { key: 'backgroundColor', label: 'Background Color', type: 'color' },
      { key: 'accentColor', label: 'Hover Accent Color', type: 'color' },
      { key: 'textColor', label: 'Link Text Color', type: 'color' },
      { key: 'borderColor', label: 'Border Color', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'text' },
    ],
  },

  // ─── DYNAMIC (Live-data) Components ───────────────────────────────────────
  // These components fetch live data from the tenant's backend API.
  // In the builder, they show placeholder data. On live sites, they fetch real data.

  DynamicNotifications: {
    category: 'Content',
    label: '🔔 Live Notifications Board',
    defaultProps: {
      title: 'Important Notices',
      limit: 5,
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'limit', label: 'Max Notices to Show', type: 'number' },
    ],
  },

  DynamicProductCatalogue: {
    category: 'E-commerce',
    label: '🛒 Live Product Catalogue',
    defaultProps: {
      title: 'Our Catalogue',
      columns: 3,
    },
    propSchema: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'columns', label: 'Grid Columns', type: 'number' },
    ],
  },
};

